[FM-2578] integrate with FE
neurio/alert-info-generator pull request #6
Opened 2021-08-20 23:04 UTC by a-sirenko

## Jira Story
* [Jira Link](https://neurio.atlassian.net/browse/FM-2578)

## Description
Fixing the error:
```
Access to fetch at 'https://pwrfleet-stg-alert-info.s3.amazonaws.com/battery/default.json' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
And making alertType and deviceType values upper-case in the document to match frontend definitions.

## Check if the PR fulfills these requirements
- [ ] Existing tests are passing
- [ ] Tests for the changes have been added 
- [ ] Documentations have been added / updated 
- [x] Manually tested the changes

2021-08-21 00:20 UTC, wnstck requested changes

2021-08-21 00:20 UTC, wnstck commented on cdk/generated_files/generated_files_stack.py
> +            allowed_origins.append(f"https://fleet-{deployment_env}.neurio")
`neur.io`

2021-08-21 12:09 UTC, a-sirenko commented on cdk/generated_files/generated_files_stack.py
> +            allowed_origins.append(f"https://fleet-{deployment_env}.neurio")
Good catch, updated.

2021-08-23 22:33 UTC, NickLiuVan approved these changes
👍

2021-08-23 23:27 UTC, mancap approved these changes

2021-08-23 23:29 UTC, merged